//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookings
    {
        public int BookingID { get; set; }
        public int bookingState { get; set; }
        public int CarsNumber { get; set; }
        public System.DateTime BookingDate { get; set; }
        public bool Driver { get; set; }
        public bool Delivery { get; set; }
        public string Note { get; set; }
        public Nullable<int> Car_CarID { get; set; }
        public Nullable<int> Invoice_InvoiceID { get; set; }
        public Nullable<int> User_UserID { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Invoices Invoices { get; set; }
        public virtual Users Users { get; set; }
    }
}
