//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Bookings = new HashSet<Bookings>();
            this.Images = new HashSet<Images>();
            this.Rates = new HashSet<Rates>();
        }
    
        public int CarID { get; set; }
        public int SerialNumber { get; set; }
        public string Note { get; set; }
        public int Fuel { get; set; }
        public double LoanMinPrice { get; set; }
        public double PricePerHour { get; set; }
        public double PricePerDay { get; set; }
        public double PricePerMonth { get; set; }
        public int seatNumber { get; set; }
        public int Gear { get; set; }
        public Nullable<int> CarModel_CarModelID { get; set; }
        public Nullable<int> Category_CategoryID { get; set; }
        public Nullable<int> CreationYear_CreationYearID { get; set; }
        public Nullable<int> TypeCar_TypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
        public virtual CarModels CarModels { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual CreationYears CreationYears { get; set; }
        public virtual TypeCars TypeCars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Images> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rates> Rates { get; set; }
    }
}
