//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture
{
    using System;
    using System.Collections.Generic;
    
    public partial class States
    {
        public int StateID { get; set; }
        public string StateName { get; set; }
        public Nullable<int> Country_CountryID { get; set; }
    
        public virtual Countries Countries { get; set; }
    }
}
