//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategories
    {
        public int SubCategoryID { get; set; }
        public string Name { get; set; }
        public float Subscription { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Category_CategoryID { get; set; }
    
        public virtual Categories Categories { get; set; }
    }
}
